openapi: 3.0.0
info:
  title: Test
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /time:
    get:
      summary: time
      tags: []
      responses:
        '200':
          description: OK
          headers:
            header-0:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples: {}
      operationId: get-time
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
